name: Test & deploy to npm

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.3.0-alpine
      - name: Install dependencies
        run: |
          cd javascript
          npm install
      - name: Run tests
        run: npm run test
      - name: Deploy to npm
        if: success()
        run: npm publish