name: Test & deploy to npm

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          cd javascript/
          npm install
      - name: Get current version
        run: |
          cd javascript/
          npm version --no-git-tag-version patch
      - name: Increment version
        run: |
          cd javascript/
          npm version patch
      - name: Commit and push new version
        run: |
          cd javascript/
          git add package.json
          git config --global user.email ${{ secrets.USER_EMAIL_GITHUB }}
          git config --global user.name ${{ secrets.USER_NAME_GITHUB }}
          git commit -m "Release v$(node -p "require('./package.json').version")"
          git push
      - name: Run tests
        run: |
          cd javascript/
          npm run test
      - name: Deploy to npm
        if: success()
        run: |
          cd javascript/
          npm publish /src
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
