name: Test & Deploy to PyPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd python/
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: |
        pytest
    - name: Deploy to PyPI
      if: success()
      run: |
        cd python/
        python setup.py sdist upload
        twine check dist/*
        twine upload --skip-existing dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISH }}
