name: Test & Deploy to PyPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TWINE_TOKEN: ${{ secrets.PYPI_PUBLISH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd python/
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: |
        pytest
    - name: Deploy to PyPI
      if: success()
      run: |
        cd python/
        python setup.py sdist upload
        twine check dist/*
        twine upload --repository-url https://pypi.org/project/legacy/opensourceducation/ -u __token__ -p "$TWINE_TOKEN" --skip-existing dist/*
      